### ISSUE TITLE
Allow resizing of the sidebar in the web app

### ISSUE THREAD

**Issue by ryankscott** [ryankscott/finish-em#458]
Allow resizing of the sidebar in the web app, as well as adding a collapse button.

**Comment by ryankscott** [comment]
🤖 Coding Agent Spec
## Feature Summary

Allow users to resize the web app sidebar by dragging its right edge, and add a dedicated collapse/expand button within the sidebar itself. Currently the sidebar is fixed at `w-60` (240px) and can only be toggled via the `\` keyboard shortcut — there's no visible UI control for it.

## Acceptance Criteria

- [ ] **Resize handle**: A drag handle on the right edge of the sidebar. Dragging left/right resizes the sidebar width.
- [ ] **Min/max constraints**: Width clamped between ~180px (min, to keep icons visible) and ~480px (max, to not overwhelm the content area).
- [ ] **Width persistence**: The chosen width is persisted to `localStorage` and restored on next visit.
- [ ] **Collapse button**: A visible button (e.g. `PanelLeftClose` icon) inside the sidebar that toggles sidebar visibility.
- [ ] **Expand affordance when hidden**: When the sidebar is collapsed, show a small visible affordance (e.g. a thin strip or a floating `PanelLeftOpen` button) so users can re-open it without knowing the `\` shortcut.
- [ ] **Keyboard shortcut still works**: The existing `\` hotkey continues to toggle sidebar visibility.
- [ ] **Smooth UX**: During drag, use `user-select: none` and `cursor: col-resize` to prevent text selection and show appropriate cursor.
- [ ] **Dark + light theme**: Resize handle and collapse button look correct in both themes.

## Technical Approach

**Surface**: Web only (`src/web/`). The TUI has its own separate sidebar.

### Approach: Custom resize handle (no new dependency)

The project already uses Radix UI primitives but does not have `@radix-ui/react-resizable`. To keep dependencies minimal and avoid a shadcn install cycle, implement a lightweight custom resize handle using React refs + mouse events. This is a well-established pattern for resizable panels.

### Files to Modify

| File | Changes |
|---|---|
| `src/web/state/ui.tsx` | Add `sidebarWidth: number` state (default 240, persisted to `localStorage`). Add `setSidebarWidth` setter. Keep `sidebarVisible` / `toggleSidebar` as-is. |
| `src/web/components/Sidebar.tsx` | Replace fixed `w-60` with dynamic width from `ui.sidebarWidth`. Add collapse button. Add resize handle element on the right edge. When `sidebarVisible` is false, render a thin collapsed strip instead of `null`. |
| `src/web/components/AppShell.tsx` | Minor: may need to adjust the layout so the collapsed strip is positioned correctly. |
| `src/web/styles.css` | Add `user-select: none` and `cursor: col-resize` utility classes for the resize handle if needed. |

### Implementation Plan

1. **`ui.tsx` — add `sidebarWidth` state** (lines ~53, 86)
   - New `useState<number>` with initial value from `localStorage.getItem("sidebarWidth") ?? 240`
   - `useEffect` to persist to `localStorage` on change
   - Expose `sidebarWidth` and `setSidebarWidth` on `UiState`
   - Clamp in the setter or where consumed: min 180, max 480

2. **`Sidebar.tsx` — resize handle + collapse button** (lines ~171-264)
   - Replace `className="flex w-60 shrink-0 ..."` with dynamic width using `ui.sidebarWidth`
   - Add a `div` resize handle (4–6px wide, `cursor: col-resize`) at the right edge of the sidebar
   - Implement `onMouseDown` → `onMouseMove` → `onMouseUp` drag logic with `useRef` for tracking
   - Add `useEffect` to attach `mousemove`/`mouseup` to `document` (clean up on unmount)
   - Set `document.body.style.userSelect = "none"` during drag, restore on mouseup
   - Add a collapse button in the sidebar header area (top or bottom) using `PanelLeftClose` from `lucide-react`
   - **Collapsed state**: When `!ui.sidebarVisible`, render a thin `<aside>` strip (~36px) with a `PanelLeftOpen` button to re-open, instead of returning `null`

3. **`AppShell.tsx`** (line ~63-64)
   - The existing `flex h-full` layout should work fine since `shrink-0` is already on the sidebar. No changes expected, but verify after sidebar changes.

4. **`styles.css`**
   - Add `.resize-handle` and `.resize-handle:hover` styles for the handle appearance (subtle border effect, matches theme colors)

### Test Plan

Web tests: The web side doesn't have existing component tests (all tests are in `src/tui/` via `bun test`). Since this is a pure UI interaction feature (mouse drag, cursor changes), testing will be manual:

1. `bun run web:dev` — open the web app
2. **Verify initial width**: Sidebar loads at 240px (default) or previously persisted width
3. **Verify resize**: Drag the right edge of the sidebar left → width decreases. Drag right → width increases
4. **Verify constraints**: Cannot resize below ~180px or above ~480px
5. **Verify collapse button**: Click the collapse button → sidebar hides, thin strip appears. Click expand → sidebar reopens at last width
6. **Verify keyboard**: Press `\` → toggles sidebar visibility
7. **Verify persistence**: Resize to a custom width, refresh the page → width is restored
8. **Verify theme**: Toggle dark/light mode → handle and button look correct
9. **Verify no text selection**: During drag, text in the page is not accidentally selected

### Open Questions

- **Collapse button placement**: Top-right of sidebar (near project count area), or bottom of sidebar? **Recommendation**: Bottom of sidebar, above the projects section, to keep it accessible but out of the way of navigation items.
- **Collapsed strip width**: ~36px matches the icon size + padding. **Recommendation**: 40px for comfortable clicking.
- **Animate width transition?** CSS `transition` on the width for the collapse/expand could feel nice but would interfere with drag responsiveness. **Recommendation**: No animation on width — keep it instant. The collapse button provides the only animated affordance.
- **Resize handle visibility**: Always visible or only on hover? **Recommendation**: Subtle always-visible border that brightens on hover to indicate draggability.

**Comment by ryankscott** [comment]
>Collapse button placement: Top-right of sidebar (near project count area), or bottom of sidebar? Recommendation: Bottom of sidebar, above the projects section, to keep it accessible but out of the way of navigation items.

I'd prefer top-right

> Collapsed strip width: ~36px matches the icon size + padding. Recommendation: 40px for comfortable clicking.

Sounds good 

> Animate width transition? CSS transition on the width for the collapse/expand could feel nice but would interfere with drag responsiveness. Recommendation: No animation on width — keep it instant. The collapse button provides the only animated affordance.

Let's start with no animation. 

> Resize handle visibility: Always visible or only on hover? Recommendation: Subtle always-visible border that brightens on hover to indicate draggability.

Do recommendation. 

LGTM, please build.

**Comment by ryankscott** [comment]
👀 PR #460 feedback received: build is broken. The change to `src/web/components/HelpDialog.tsx` is invalid. Transitioning back to `agent:build` for fixes.

**Comment by ryankscott** [comment]
Fixed the broken build in PR #460. The  file had invalid backslash escaping that was causing a TypeScript compilation error. The line:



has been corrected to:



The fix has been pushed to the PR branch. Ready for re-review.
